-- 📋 ER Diyagramı Revizyon Listesi (Notlar)
-- 1. Zayıf Varlık (Weak Entity) Düzeltmesi:
-- Hata: Şu anki diyagramda STOP (Durak) kutusu tek çizgili bir dikdörtgen olarak çizilmiş.
-- Düzeltme: STOP kutusunun çerçevesi Çift Çizgili Dikdörtgen yapılmalı.
-- Nedeni: Duraklar, bir Rota (ROUTE) olmadan tek başlarına var olamazlar (Existence Dependency).

-- 2. Tanımlayıcı İlişki (Identifying Relationship) Düzeltmesi:
-- Hata: ROUTE ile STOP arasındaki Has (Sahip Olma) ilişkisini gösteren baklava dilimi tek çizgili.
-- Düzeltme: Has baklava diliminin çerçevesi Çift Çizgili yapılmalı.
-- Nedeni: Bu ilişki, zayıf varlığı (Durak) güçlü varlığa (Rota) bağlayan "Tanımlayıcı İlişki"dir.

-- 3. Yazım Hatası (Typo) Düzeltmesi:
-- Hata: Participations ile ilişkili olan nitelik kutusunda is_complated yazıyor.
-- Düzeltme: Kelime is_completed olarak düzeltilmeli.
-- Nedeni: Veritabanındaki sütun adı is_completed. Hem İngilizce doğrusu bu, hem de kodla uyumlu olmalı.


-- 1. Sequence Oluşturma (Proje İsteri: Sequence Kullanımı)
-- Bu sequence sadece participations tablosu için kullanılacak.
-- Çünkü bu tablo daha dinamik/değişkendir. 
-- id işlemleri(id sıfırlama vs.) daha yoğun gerçekleşebileceği için mantıklıdır
-- Eventler oluyor siliniyor katılımcılar değişiyor sonra id 100000 oluyor.
-- id 100000den sonra atıyorum sıfırdan tekrar başlatma fln sağlarmış.
CREATE SEQUENCE participations_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- 2. Tabloların Oluşturulması

CREATE TABLE "users" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "role" varchar NOT NULL DEFAULT 'user',
  "total_points" integer DEFAULT 0,
  "created_at" timestamp DEFAULT (now()),
  -- İster: Sayı Kısıtı (Puan negatif olamaz)
  CONSTRAINT check_positive_points CHECK (total_points >= 0)
);

CREATE TABLE "user_hobbies" (
  "hobby_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "hobby_name" varchar NOT NULL
);

CREATE TABLE "routes" (
  "route_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "creator_id" integer,
  "route_name" varchar NOT NULL,
  "distance_km" decimal NOT NULL,
  "difficulty_level" varchar,
  "created_at" timestamp DEFAULT (now()),
  -- İster: Sayı Kısıtı (Mesafe 0 veya negatif olamaz)
  CONSTRAINT check_positive_distance CHECK (distance_km > 0)
);

CREATE TABLE "stops" (
  "stop_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "route_id" integer,
  "stop_order" integer NOT NULL,
  "location_name" varchar NOT NULL
);

CREATE TABLE "events" (
  "event_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "organizer_id" integer,
  "route_id" integer,
  "event_date" timestamp NOT NULL,
  "status" varchar DEFAULT 'active',
  "description" text,
  -- İster: Veri kısıtı (Sadece belirli durumlar girilebilir)
  CONSTRAINT check_event_status CHECK (status IN ('active', 'completed', 'cancelled'))
);

CREATE TABLE "participations" (
  -- Burada yukarıda oluşturduğumuz Sequence'i kullanıyoruz
  "participation_id" INTEGER DEFAULT nextval('participations_seq') PRIMARY KEY,
  "user_id" integer,
  "event_id" integer,
  "join_date" timestamp DEFAULT (now()),
  "is_completed" boolean DEFAULT false
);

-- 3. Foreign Key Tanımları

ALTER TABLE "user_hobbies" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE;

ALTER TABLE "routes" ADD FOREIGN KEY ("creator_id") REFERENCES "users" ("user_id");

ALTER TABLE "stops" ADD FOREIGN KEY ("route_id") REFERENCES "routes" ("route_id") ON DELETE CASCADE;

ALTER TABLE "events" ADD FOREIGN KEY ("organizer_id") REFERENCES "users" ("user_id");

ALTER TABLE "events" ADD FOREIGN KEY ("route_id") REFERENCES "routes" ("route_id");

ALTER TABLE "participations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "participations" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("event_id") ON DELETE CASCADE;