CREATE TABLE "users" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "role" varchar NOT NULL DEFAULT 'user',
  "total_points" integer DEFAULT 0,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "user_hobbies" (
  "hobby_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "hobby_name" varchar NOT NULL
);

CREATE TABLE "routes" (
  "route_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "creator_id" integer,
  "route_name" varchar NOT NULL,
  "distance_km" decimal NOT NULL,
  "difficulty_level" varchar,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "stops" (
  "stop_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "route_id" integer,
  "stop_order" integer NOT NULL,
  "location_name" varchar NOT NULL
);

CREATE TABLE "events" (
  "event_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "organizer_id" integer,
  "route_id" integer,
  "event_date" timestamp NOT NULL,
  "status" varchar DEFAULT 'active',
  "description" text
);

CREATE TABLE "participations" (
  "participation_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "event_id" integer,
  "join_date" timestamp DEFAULT (now()),
  "is_completed" boolean DEFAULT false
);

ALTER TABLE "user_hobbies" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE;

ALTER TABLE "routes" ADD FOREIGN KEY ("creator_id") REFERENCES "users" ("user_id");

ALTER TABLE "stops" ADD FOREIGN KEY ("route_id") REFERENCES "routes" ("route_id") ON DELETE CASCADE;

ALTER TABLE "events" ADD FOREIGN KEY ("organizer_id") REFERENCES "users" ("user_id");

ALTER TABLE "events" ADD FOREIGN KEY ("route_id") REFERENCES "routes" ("route_id");

ALTER TABLE "participations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "participations" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("event_id") ON DELETE CASCADE;
